# Generated by Django 2.0.13 on 2020-01-17 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='date_publicacao',
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 21, 39, 31, 45293, tzinfo=utc)),
        ),
    ]
