# Generated by Django 2.0.13 on 2020-01-19 18:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200117_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Area'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 19, 18, 16, 13, 528461, tzinfo=utc)),
        ),
    ]
